#!/bin/bash
# Phase 4: re-run flashgg Impact plots + Bias study on the 5-feature datacards/envelope.
# Everything else OFF (scoring/cut/limits already done). AN push held. Held-tolerant grand.
set -uo pipefail
cd /afs/cern.ch/work/p/pelai/HZa/HiggsZaAna

RUN_HIGGSZA_CLEAN_OUTPUTS=0 \
RUN_HIGGSZA_MERGE_PARQUET=0 \
RUN_HIGGSZA_P2ROOT=0 \
RUN_HIGGSZA_TRAIN_MVA=0 \
RUN_HIGGSZA_P2ROOT_MVA_SCORE=0 \
RUN_HIGGSZA_DETERMINE_MVA_CUT=0 \
RUN_HIGGSZA_PLOT=0 \
RUN_FLASHGG_ENV=1 \
RUN_FLASHGG_MVA_CUT=0 \
RUN_FLASHGG_TREE2WS=0 \
RUN_FLASHGG_BACKGROUND=0 \
RUN_FLASHGG_SIGNAL=0 \
RUN_FLASHGG_DATACARD=0 \
RUN_FLASHGG_COMBINE_LIMITS=0 \
RUN_FLASHGG_PLOT_LIMITS=0 \
RUN_FLASHGG_IMPACT=1 \
RUN_FLASHGG_BIAS=1 \
RUN_FLASHGG_COLLECT_BKG=0 \
RUN_EXIT_CMSSW_ENV=1 \
RUN_UPDATE_AN=0 \
bash 1_grand.sh
