#!/bin/bash
# 5-feature low-mass model rerun: re-score -> cuts -> flashgg -> limits.
# AN push held (RUN_UPDATE_AN=0). IMPACT/BIAS off (beyond limits).
# Launch from HiggsZaAna dir with a VALID voms proxy already initialized.
set -uo pipefail
cd /afs/cern.ch/work/p/pelai/HZa/HiggsZaAna

RUN_HIGGSZA_CLEAN_OUTPUTS=0 \
RUN_HIGGSZA_MERGE_PARQUET=0 \
RUN_HIGGSZA_P2ROOT=0 \
RUN_HIGGSZA_TRAIN_MVA=0 \
RUN_HIGGSZA_P2ROOT_MVA_SCORE=1 \
RUN_HIGGSZA_P2ROOT_MVA_SCORE_INITIAL=1 \
RUN_HIGGSZA_P2ROOT_MVA_SCORE_RESUBMIT=1 \
RUN_HIGGSZA_DETERMINE_MVA_CUT=1 \
RUN_HIGGSZA_DETERMINE_MVA_CUT_INITIAL=1 \
RUN_HIGGSZA_DETERMINE_MVA_CUT_RESUBMIT=1 \
RUN_HIGGSZA_PLOT=1 \
RUN_FLASHGG_ENV=1 \
RUN_FLASHGG_MVA_CUT=1 \
RUN_FLASHGG_TREE2WS=1 \
RUN_FLASHGG_BACKGROUND=1 \
RUN_FLASHGG_SIGNAL=1 \
RUN_FLASHGG_DATACARD=1 \
RUN_FLASHGG_COMBINE_LIMITS=1 \
RUN_FLASHGG_PLOT_LIMITS=1 \
RUN_FLASHGG_IMPACT=0 \
RUN_FLASHGG_BIAS=0 \
RUN_FLASHGG_COLLECT_BKG=1 \
RUN_EXIT_CMSSW_ENV=1 \
RUN_UPDATE_AN=0 \
bash 1_grand.sh
